model: "gpt-4o-mini"
# model: "anthropic/claude-sonnet-4-6"
retrieve_model: "gpt-4o-mini" 
toc_check_page_num: 50
max_page_num_each_node: 20
max_token_num_each_node: 20000
if_add_node_id: "yes"
if_add_node_summary: "yes"
if_add_doc_description: "no"
if_add_node_text: "no"